# Generated by Django 4.1.1 on 2022-10-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='name',
        ),
    ]
