# Generated by Django 4.1.2 on 2022-10-18 12:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0002_remove_nurse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kardex',
            name='age',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='bedNum',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='doctorInCharge',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='hospitalName',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='patientName',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='sex',
        ),
        migrations.AddField(
            model_name='kardex',
            name='ageSex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='diet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='drs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='dx',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='extraFieldValues',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='kardex',
            name='extraFields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='kardex',
            name='ivf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='laboratoryWorkUps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='nameOfWard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='referrals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='sideDrip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='specialNotations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='hospitalNum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
