# Generated by Django 4.1.2 on 2022-10-18 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0003_remove_kardex_age_remove_kardex_bednum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kardex',
            old_name='dateTime',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='kardex',
            old_name='extraFieldValues',
            new_name='extra_field_values',
        ),
        migrations.RenameField(
            model_name='kardex',
            old_name='extraFields',
            new_name='extra_fields',
        ),
        migrations.RenameField(
            model_name='kardex',
            old_name='hospitalNum',
            new_name='hospital_num',
        ),
        migrations.RenameField(
            model_name='kardex',
            old_name='laboratoryWorkUps',
            new_name='laboratory_work_ups',
        ),
        migrations.RenameField(
            model_name='kardex',
            old_name='nameOfWard',
            new_name='name_of_ward',
        ),
        migrations.RenameField(
            model_name='kardex',
            old_name='sideDrip',
            new_name='side_drip',
        ),
        migrations.RenameField(
            model_name='kardex',
            old_name='specialNotations',
            new_name='special_notations',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='ageSex',
        ),
        migrations.AddField(
            model_name='kardex',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='kardex',
            name='sex',
            field=models.CharField(blank=True, default='Male', max_length=255, null=True),
        ),
    ]
