# Generated by Django 4.1.2 on 2022-10-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0005_kardex_labelmarkers_kardex_labelvalues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kardex',
            old_name='labelMarkers',
            new_name='label_markers',
        ),
        migrations.RenameField(
            model_name='kardex',
            old_name='labelValues',
            new_name='label_values',
        ),
    ]
