# Generated by Django 4.1.2 on 2022-10-21 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0007_alter_kardex_extra_field_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(0)]),
        ),
    ]
