# Generated by Django 4.1.2 on 2022-10-22 07:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0008_kardex_date_added_alter_kardex_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='edited_at',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now_add=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='kardex',
            name='edited_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
