# Generated by Django 4.1.2 on 2022-10-22 15:21

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0009_nurse_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalKardex',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name_of_ward', models.CharField(blank=True, max_length=255, null=True)),
                ('ivf', models.TextField(blank=True, null=True)),
                ('laboratory_work_ups', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('side_drip', models.TextField(blank=True, null=True)),
                ('special_notations', models.TextField(blank=True, null=True)),
                ('referrals', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(0)])),
                ('sex', models.CharField(blank=True, default='Male', max_length=255, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('hospital_num', models.CharField(blank=True, max_length=255, null=True)),
                ('dx', models.TextField(blank=True, null=True)),
                ('drs', models.CharField(blank=True, max_length=255, null=True)),
                ('diet', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('extra_field_values', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None)),
                ('label_markers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('label_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('edited_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('edited_at', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now_add=True), blank=True, null=True, size=None)),
                ('date_added', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical kardex',
                'verbose_name_plural': 'historical kardexs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
