# Generated by Django 4.1.2 on 2022-10-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0010_historicalkardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
