# Generated by Django 4.1.2 on 2022-10-31 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0011_nurse_department_nurse_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkardex',
            name='extra_field_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalkardex',
            name='extra_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalkardex',
            name='label_markers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalkardex',
            name='label_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='extra_field_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='extra_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='label_markers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='label_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=255), blank=True, null=True, size=None),
        ),
    ]
