# Generated by Django 4.1.2 on 2022-11-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0013_alter_kardex_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='nurse_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
