# Generated by Django 4.1.2 on 2022-11-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0015_nurse_on_duty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalkardex',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='kardex',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='historicalkardex',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
