# Generated by Django 4.1.2 on 2022-11-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0016_rename_name_historicalkardex_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalkardex',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical kardex'},
        ),
        migrations.AlterField(
            model_name='historicalkardex',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
