# Generated by Django 4.1.2 on 2022-11-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0017_alter_historicalkardex_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkardex',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
