# Generated by Django 4.1.2 on 2022-11-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kardex_app", "0020_alter_historicalkardex_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalkardex",
            name="bed_num",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="kardex",
            name="bed_num",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
