# Generated by Django 4.1.2 on 2022-11-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kardex_app", "0021_historicalkardex_bed_num_kardex_bed_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalkardex",
            name="case_num",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="kardex",
            name="case_num",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
