# Generated by Django 4.1.2 on 2022-11-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kardex_app", "0023_historicalkardex_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalkardex",
            name="is_admission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalkardex",
            name="is_death",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalkardex",
            name="is_discharges",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalkardex",
            name="is_trans_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalkardex",
            name="is_trans_other",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalkardex",
            name="is_trans_out",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kardex",
            name="is_admission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kardex",
            name="is_death",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kardex",
            name="is_discharges",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kardex",
            name="is_trans_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kardex",
            name="is_trans_other",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kardex",
            name="is_trans_out",
            field=models.BooleanField(default=False),
        ),
    ]
