# Generated by Django 4.1.2 on 2022-11-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0024_historicalkardex_is_admission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkardex',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='diagnosis',
        ),
    ]
